version = 0.1
[default.pipeline_bootstrap.parameters]
pipeline_user = "arn:aws:iam::654654614431:user/aws-sam-cli-managed-dev-pipeline-resou-PipelineUser-KJ4YJaVCaRrn"
permissions_provider = "AWS IAM"

[dev.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::654654614431:role/aws-sam-cli-managed-dev-pipel-PipelineExecutionRole-jw9NnGEJqrO3"
cloudformation_execution_role = "arn:aws:iam::654654614431:role/aws-sam-cli-managed-dev-p-CloudFormationExecutionRo-LltfX9FxFBEq"
artifacts_bucket = "aws-sam-cli-managed-dev-pipeline-r-artifactsbucket-rwu1jzlo31i7"
image_repository = ""
region = "us-west-2"

[prod.pipeline_bootstrap.parameters]
pipeline_execution_role = "arn:aws:iam::654654614431:role/aws-sam-cli-managed-prod-pipe-PipelineExecutionRole-wAgYkHwb0Zw5"
cloudformation_execution_role = "arn:aws:iam::654654614431:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-haBIXRnHyjQf"
artifacts_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-dwlr3gr4aj1a"
image_repository = ""
region = "us-west-2"
